docker buildx build \
            --target framework \
            --platform linux/amd64 \
            -f docker/Dockerfile \
            --build-arg CUDA_VERSION="12.9.1" \
            --build-arg BUILD_TYPE="all" \
            --build-arg GRACE_BLACKWELL=0 \
            --build-arg INSTALL_FLASHINFER_JIT_CACHE=1 \
            --build-arg SGL_VERSION=v0.5.7dev \
            -t ophoperhpo/sglang-qwen:v0.5.7dev-cu129-amd64 \
            --no-cache .
